### ISSUE TITLE
New Hama colors 95 - 98

### ISSUE THREAD

**Issue by galaxyAbstractor** [maxcleme/beadcolors#28]
Hama has added some new colors recently, namely 95 - 98

https://www.hama.dk/media/102647/colour-chart.pdf
https://www.hama.dk/media/102654/99199_artikel1.pdf

I was looking into adding them myself and submitting a PR, but I am unsure what method should be used to properly get an approximate color. I tried color picking the beads in the second PDF in gimp to compare them with the values for the current colors but they were a bit off so I am uncertain if this is an acceptable approach or if there is a more proper way? Also the images in the PDF is kinda low quality so depending on where you pick the color it can vary.

**Comment by maxcleme** [comment]
Thanks for notifying this ! I wasn't aware of this new colors.

Sadly we don't really have a proper way to infer color reference (rgb or whatever) from these.

I guess the best way is still to get them in hand and try to look for reference that looks good enough to be satisfied (be careful of your own screen, since it could not display color properly as well).

I also heard of people using advanced tools like color muse, but I never got my hands on those.

Ideally this repository is here to be adjusted over time, so I don't really have a problem of adding those colors even if the reference are approximated for now. Hopefully people could refine those over time and find a agreement.

It might also be worth it to try to contact Hama color reference contributor for better advice about sampling : 

+ @jeppewl (looks like I can't tag him)
+ LThanda (which is @dpalay if I'm not mistaken)

**Comment by galaxyAbstractor** [comment]
I've created pull request #29 with approximate colors using color picker on the Hama color chart for now

**Comment by jeppewl** [comment]
Hi @maxcleme I haven't worked with beads for a while so I wasn't aware there were new colors. I have just ordered them and will sample their RGB values from a photography, as I have done previously https://docs.google.com/spreadsheets/d/1Ordv1eQV0HszqxWJf5oM4alch4Q2v5dtiJb-Vui8Rh0/edit?usp=sharing

**Comment by maxcleme** [comment]
@galaxyAbstractor Thanks for contribution, I'll accept your MR and release the new version of Beadcolors (and they should be available directly from Beadifier as well)

@jeppewl Thanks in advance for this, you are going to merge the current sample in order to make them available asap, however feel free to correct those once your sample is done if you think it is necessary.

**Comment by jeppewl** [comment]
Here are my photo-based samples of the four new hama colors, as well as no. 33 which I found out is also a normal, opaque color.
```
33 | Cherise |  #fe1327
95 | Pastel rose | #dd9ba3
96 | Pastel lilac  | #b491ad
97 | Pastel ice blue | #8aafc2
98 | Pastel mint | #94cca4
```

**Comment by maxcleme** [comment]
@jeppewl Thx for contribution, I'll update them asap.
