### ISSUE TITLE
Layout

### ISSUE THREAD

**Issue by David204354** [maxcleme/beadcolors#43]
So I noticed when using your website that you can't tell the difference between the background and the (object) so if you could fix it that would be great. and if you could do feedback my email I want to send back is davidstawhat1234@gmail.com

**Comment by David204354** [comment]
Like this 
![Screenshot 2024-05-12 1 44 46 PM](https://github.com/maxcleme/beadcolors/assets/169614313/cb82294f-cd9f-4886-8f18-26c4604097a0)

**Comment by David204354** [comment]
Im saying the picture that i replied to mixed up the background and the
thing/subject

**Comment by maxcleme** [comment]
I got it, did you try any of the solution I suggested? 😅 

Do you mind sharing the original picture as well? I can't help here without further information.

**Comment by David204354** [comment]
[image: download.jpg]here

**Comment by David204354** [comment]
I Meant this
[image: download.jpg]

**Comment by maxcleme** [comment]
I can't see anything, do you mind going directly to Github and use the website instead? This is what I got:

> I Meant this
[image: download.jpg]

**Comment by David204354** [comment]
Sorry about that
![download](https://github.com/maxcleme/beadcolors/assets/169614313/3c3998e9-1a3d-493c-bf8c-4d5e66cd68ed)

**Comment by maxcleme** [comment]
Considering the previous picture you sent, this image is obviously cropped and low-res. With such material I've no idea about what the expected pattern size. 

However, from what I can guess, you seem to be trying to make what I assumed to be a plushy into a bead pattern. The issue with the outline is that the white background pixels coalesce with the subject outline pixels. 

See the outlined area:
![Screenshot 2024-05-14 at 19 27 10](https://github.com/maxcleme/beadcolors/assets/7669401/b0720a7e-e7f9-4530-bd72-bb9b0244dde4)

The tool is working on a pixel-basis so there is no way it can differentiate the white background pixel from a white object pixel. In such scenario my usual trick is to replace the white background with transparent, making then the distinction clear between background and object. I did this with your picture and you can see it doesn't even sure a bead for the background (because of transparency), outlining the object much better:
![Screenshot 2024-05-14 at 19 35 12](https://github.com/maxcleme/beadcolors/assets/7669401/05c1b18a-79ee-46a0-b2f3-3ffbc22561b6)

This is what I used instead:
![330479374-3c3998e9-1a3d-493c-bf8c-4d5e66cd68ed](https://github.com/maxcleme/beadcolors/assets/7669401/d5711c24-9f76-4298-8a6e-96441084797e)

**Comment by David204354** [comment]
Do you have a suggestion for the backgrounds being transparent?

**Comment by maxcleme** [comment]
Not really, there is plenty of tools out there 😅
